import {
  Baby,
  Briefcase,
  Cake,
  Camera,
  Check,
  Disc3,
  Flower2,
  Gem,
  GraduationCap,
  Handshake,
  Heart,
  Martini,
  Music4,
  PartyPopper,
  Presentation,
  Search,
  Sparkles,
  Utensils,
  Wine,
} from 'lucide-react'

export const ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  gem: Gem,
  heart: Heart,
  cake: Cake,
  baby: Baby,
  briefcase: Briefcase,
  'party-popper': PartyPopper,
  'graduation-cap': GraduationCap,
  presentation: Presentation,
  wine: Wine,
  sparkles: Sparkles,
  martini: Martini,
  utensils: Utensils,
  disc: Disc3,
  flower: Flower2,
  camera: Camera,
  music: Music4,
  check: Check,
  handshake: Handshake,
  search: Search,
}
